projectName: itu-somalia
apiVersion: unicccloud.org/v1alpha1
kind: CWHv2
security:
  enabled: true
apps:
  - name: alb-ingress
    appType: alb-ingress
    version: 0.0.15
    values:
      certificatesArn: "arn:aws:acm:eu-west-1:488638853303:certificate/96c3ec94-fbfe-4650-876e-03c4681a2b58, arn:aws:acm:eu-west-1:488638853303:certificate/3520c643-2493-4ee6-97d5-76f86fea58bc, arn:aws:acm:eu-west-1:488638853303:certificate/ff1dbdc2-1356-4dba-bdd5-805efba32473"
      hosts:
        - hostNames:
            - "itu-somalia.leman.un-icc.cloud"
            - "somalia.gov.so"
            - "www.somalia.gov.so"
          appName: web
  - name: web
    appType: standard-app
    version: 0.0.38
    dockerfile: Dockerfile
    values:
      cpu: 800m
      memory: 2048Mi
      containerPort: 8080
      postDeployScript: "./postDeploy.sh"
      replicaCount: 2
      secret:
        - name: DB_HOST
          secret_key: db_host
        - name: DB_PASSWORD
          secret_key: user_db_password
        - name: SMTP_USER
          secret_key: aws_access_key
        - name: SMTP_PASSWORD
          secret_key: aws_smtp_password
        - name: AWS_SECRET_ACCESS_KEY
          secret_key: aws_secret_access_key
        - name: AWS_ACCESS_KEY_ID
          secret_key: aws_access_key
      env:
        ENV: prod
        UNICC: true
        DB_USER: itusomalia
        DB_NAME: itusomalia
        TYPO3_CONTEXT: Production/unicc
        HOST_SOMALIA: https://www.somalia.gov.so/
      sharedStorage:
        enabled: true
        mountPaths:
          - /var/www/public/fileadmin/
          - /var/www/var/
  - name: shared-storage
    appType: efs-storage
    version: 0.0.10

  - name: dump-tool
    appType: dump-tool
    version: 0.0.3
    values:
      schedule: "0 7 * * *"
      projectName: itu-somalia
      dbName: "itusomalia"
      dbUser: "itusomalia"

